[package]
name = "strikefi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
rocket = "0.5.0"
shuttle-rocket = "0.52.0"
shuttle-runtime = "0.52.0"
tokio = { version = "1.26.0", features = ["full"] }
sqlx = { version = "0.8.3", features = [
  "postgres",
  "runtime-tokio",
  "tls-native-tls",
] }

# Pinned to the same sui release as the CLI provided by the nix devshell
sui-sdk = { git = "https://github.com/MystenLabs/sui", tag = "testnet-v1.75.1" }
