name: Backend CI/CD

concurrency:
  group: ${{ github.ref }}-backend
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - ".sui-repo/**"
      - ".github/workflows/backend.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # install with cargo-binstall
      - name: Install cargo-binstall
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf \
            https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh \
            | bash
        shell: bash

      - name: Install cargo-shuttle
        run: cargo binstall -y --locked cargo-shuttle
        shell: bash

      # - name: Create secret file
      #   run: echo "${{ inputs.secrets }}" > Secrets.toml
      #   working-directory: ${{ inputs.working-directory }}
      #   shell: bash

      - name: Deploy to Shuttle
        working-directory: backend
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}

        # We replace the Sui dependency to point to the git repo
        run: |
          LOCAL_LINE='sui-sdk = { path = "../.sui-repo/crates/sui-sdk" }'
          REMOTE_LINE='sui_sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk"}'
          sed -i "s|$LOCAL_LINE|$REMOTE_LINE|" Cargo.toml
          cat Cargo.toml

          shuttle deploy --id proj_01JNPT0WTNBHZKNXR8M7H9RKFQ
